pipeline {
    agent any
    tools {
        jdk 'Java11'
    }
    stages {
        stage('compile') {
	         steps {
                // step1 
                echo 'compiling..'
		            git url: 'https://github.com/S-o-u-v-i-k/projCert/'
		            sh script: '/opt/maven/bin/mvn compile'
			    sh script: 'mvn -f src/main/webapp/pom.xml'
           }
        }
        stage('codereview-pmd') {
	         steps {
                // step2
                echo 'codereview..'
		            sh script: '/opt/maven/bin/mvn -P metrics pmd:pmd'
           }
	         post {
               success {
		             recordIssues enabledForFailure: true, tool: pmdParser(pattern: '**/target/pmd.xml')
               }
           }		
        }
        stage('unit-test') {
	          steps {
                // step3
                echo 'unittest..'
	               sh script: '/opt/maven/bin/mvn test'
            }
	          post {
               success {
                   junit 'target/surefire-reports/*.xml'
               }
            }			
        }
        stage('codecoverage') {

	         steps {
                // step4
                echo 'codecoverage..'
		            sh script: '/opt/maven/bin/mvn verify'
           }
	         post {
               success {
	               jacoco(execPattern: '**/build/jacoco/**.exec', classPattern: '**/classes/*/main')                  
               }
           }		
        }
        stage('package/build-war') {
	         steps {
                // step5
                echo 'package......'
		            sh script: '/opt/maven/bin/mvn package'	
           }		
        }
        stage('build & push docker image') {
	         steps {
              withDockerRegistry(credentialsId: 'DOCKER_HUB_LOGIN', url: 'https://hub.docker.com/') {
                    sh script: 'cd  $WORKSPACE'
                    sh script: 'docker build --file Dockerfile --tag docker.io/Souvik/Project1:$BUILD_NUMBER .'
                    sh script: 'docker push docker.io/Souvik/Project1:$BUILD_NUMBER'
              }	
           }		
        }
   
    }
}
